### ISSUE TITLE
UI issue with the home page of Oppia Foundation site

### ISSUE THREAD

**Issue by bansalnitish** [oppia/foundation-website#84] opened 2018-10-05 21:27 UTC
There is a major UI issue with the home page.

Here is the screenshot for the same:

![mage](https://lh3.googleusercontent.com/-gmf8lUS9p0I/W7BNidXSzJI/AAAAAAAAAMQ/pn99eySv-OQBInU4jU4QZaBfy2nrOOVSQCL0BGAYYCw/h1334/8ea167f8-c158-4eac-9ad4-f00a3ea4c29e)

This is on iPhone 6s IOS-10.3.3 on Safari Browser.

**Comment by hoangviet1993** [comment] 2018-10-08 04:39
@bansalnitish That looks pretty bad. Unfortunately I can't replicate on my ip6 ios 12 :( 

Can you post a GIF of you going to the site on your phone? I am curious how is this happening...internet connectivity maybe?

**Comment by hoangviet1993** [comment] 2018-10-13 02:31
Friendly ping @bansalnitish (are you still having problem accessing the foundation page?)

**Comment by bansalnitish** [comment] 2018-10-14 19:54
Hi @hoangviet1993 
I'm sorry for such long delay on this one. 

Yes I still can confirm the problem exists. (I don't have a on screen recorder as of now). I'll post the gif soon.

One thing to observe is that the `About`, `Contact Us`, `Follow Us` etc. section is listed at the bottom in your gif but in my phone it comes right at the start.

**Comment by hoangviet1993** [comment] 2018-11-08 17:44
@bansalnitish I will try to find a iPhone with iOS 10 to replicate this problem. I have been visiting the site on my ip6 (with iOS 12) and everything seems fine.

**Comment by seanlip** [comment] 2019-04-08 03:52
@bansalnitish just to check, do you still run into this issue?

**Comment by Gps-Gaurav** [comment] 2023-01-13 21:07
Please assign these issues

**Comment by seanlip** [comment] 2023-01-14 03:47
@Gps-Gaurav Just to check, are you able to reproduce this issue? Can you show a screen recording of what you see?

**Comment by seanlip** [comment] 2024-12-12 03:49
Closing since we are no longer maintaining this project.

**Closed by seanlip** 2024-12-12 03:49 UTC
